name: bucketeer_example
description: A sample project for using the Bucketeer.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bucketeer_flutter_client_sdk:
    path: ../
  ua_client_hints: 1.2.2
  shared_preferences: 2.2.2

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
